---
title: "Linear Models"
author: "Diana Hernandez"
date: "2023-11-09"
output: github_document
---

Load libraries and settings.

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```


# Load and clean the Airbnb data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

Let's fit the data

```{r}
fit = 
  nyc_airbnb |>
  lm(price ~ stars + borough, data = _)
```

Let's look at the `fit`

```{r}
summary(fit)
summary(fit)$coef
coef(fit)
```

Tidy the output

```{r}
fit |>
  broom::glance()
```

Tidy up the coefficients

```{r}
fit |>
  broom::tidy() |>
  mutate(term = str_replace(term, "^borough", "Borough:")) |>
  select(term, estimate, p.value) |>
  knitr::kable(digit = 3)
```

Adjusted the model

```{r}
fit =
  nyc_airbnb |>
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  ) |>
  lm(price ~ stars + borough + room_type, data = _)

fit |>
  broom::tidy()
```

# Quick look at diagnostics

```{r}
nyc_airbnb |>
  modelr::add_residuals(fit) |>
  ggplot(aes(x = borough, y = resid)) +
  geom_violin() 

nyc_airbnb |>
  modelr::add_residuals(fit) |>
  ggplot(aes(x = stars, y = resid)) +
  geom_point() 
```


# Hypothesis testing

fit a null and alternative model

```{r}
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)

fit_alternative = lm(price ~ stars + borough + room_type, data = nyc_airbnb)

anova(fit_null, fit_alternative) |>
  broom::tidy()
```

# Borough-level differences

```{r}
fit =
  nyc_airbnb |>
  lm(price ~ stars * borough + room_type * borough, data = _)

fit |>
  broom::tidy()
```

Fit separate linear model for each borough

```{r}
airbnb_lm = function(df) {
   lm(price ~ stars + room_type, data = df)
}

nyc_airbnb |>
  nest(df = -borough) |>
  mutate(
    models = map(df, airbnb_lm)
  )
```

